/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei"
import { MeshCollider, RigidBody } from "@react-three/rapier"

export default function Net(props) {
    const { nodes, materials } = useGLTF("/tennisnet.glb")

    return (
        <group {...props} dispose={null}>
            <group scale={0.49}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001.geometry}
                    material={materials.NetBelt}
                />

                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001_1.geometry}
                    material={materials.Net}
                />
                <RigidBody
                    type='fixed'
                    colliders='trimesh'
                    includeInvisible
                    friction={1}
                    restitution={1}
                >
                    <mesh
                        visible={false}
                        geometry={nodes.Collider.geometry}
                    />
                </RigidBody >
            </group>
            <RigidBody
                type='fixed'
                friction={1}
                restitution={1}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder.geometry}
                    material={materials.Pole}
                    position={[0, 0.5, 6]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder001.geometry}
                    material={materials.Pole}
                    position={[0, 0.5, -6]}
                />
            </RigidBody>
        </group>

    )
}

useGLTF.preload("/tennisnet.glb")