/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { forwardRef, useLayoutEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { TheatreJsMixamoRig } from "./TheatreJsMixamoRig";
import { mergeRefs } from "react-merge-refs";
import { LoopOnce } from "three";

export const Sophie = forwardRef((props, forwardRef) => {
  const { nodes, materials, animations } = useGLTF("/split-step.glb");
  const { ref, mixer, names, actions, clips } = useAnimations(animations);

  useLayoutEffect(() => {
    ref.current.splitStep = actions[names[0]];
    ref.current.splitStep.setLoop(LoopOnce);
  });

  // useEffect(() => {
  //   actions[names[0]].play();
  // });
  return (
    <group ref={mergeRefs([forwardRef, ref])} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="Ch02_Body"
            geometry={nodes.Ch02_Body.geometry}
            material={materials.Ch02_body}
            skeleton={nodes.Ch02_Body.skeleton}
          />
          <skinnedMesh
            name="Ch02_Cloth"
            geometry={nodes.Ch02_Cloth.geometry}
            material={materials.Ch02_body}
            skeleton={nodes.Ch02_Cloth.skeleton}
          />
          <skinnedMesh
            name="Ch02_Eyelashes"
            geometry={nodes.Ch02_Eyelashes.geometry}
            material={materials.Ch02_hair}
            skeleton={nodes.Ch02_Eyelashes.skeleton}
          />
          <skinnedMesh
            name="Ch02_Hair"
            geometry={nodes.Ch02_Hair.geometry}
            material={materials.Ch02_hair}
            skeleton={nodes.Ch02_Hair.skeleton}
          />
          <skinnedMesh
            name="Ch02_Sneakers"
            geometry={nodes.Ch02_Sneakers.geometry}
            material={materials.Ch02_body}
            skeleton={nodes.Ch02_Sneakers.skeleton}
          />
          <skinnedMesh
            name="Ch02_Socks"
            geometry={nodes.Ch02_Socks.geometry}
            material={materials.Ch02_body}
            skeleton={nodes.Ch02_Socks.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/split-step.glb");
