/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { forwardRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { TheatreJsMixamoRig } from "./TheatreJsMixamoRig";
import { mergeRefs } from "react-merge-refs";


export const Sophie = forwardRef((props, forwardRef) => {
    const { nodes, materials, animations } = useGLTF("/Sophie_nonPBR.glb");

    const { ref, mixer, names, actions, clips } = useAnimations(animations)
    useEffect(() => {
        actions[names[0]].play()
    })
    return (
        <group ref={mergeRefs([ref, forwardRef])} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <skinnedMesh
                    geometry={nodes.Ch02_Body.geometry}
                    material={materials.Ch02_body}
                    skeleton={nodes.Ch02_Body.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Ch02_Cloth.geometry}
                    material={materials.Ch02_body}
                    skeleton={nodes.Ch02_Cloth.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Ch02_Eyelashes.geometry}
                    material={materials.Ch02_hair}
                    skeleton={nodes.Ch02_Eyelashes.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Ch02_Hair.geometry}
                    material={materials.Ch02_hair}
                    skeleton={nodes.Ch02_Hair.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Ch02_Sneakers.geometry}
                    material={materials.Ch02_body}
                    skeleton={nodes.Ch02_Sneakers.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Ch02_Socks.geometry}
                    material={materials.Ch02_body}
                    skeleton={nodes.Ch02_Socks.skeleton}
                />
                <primitive object={nodes.mixamorigHips} />
                <TheatreJsMixamoRig nodes={nodes} />
            </group>
        </group>
    );
})

useGLTF.preload("/Sophie_nonPBR.glb");
